const fs = require('fs');
const path = require('path');

const toolsDir = path.join(__dirname, '../src/tools');
const indexFile = path.join(toolsDir, 'index.ts');

console.log('🔄 Refreshing tools index...');

// Get all directories in src/tools
const entries = fs.readdirSync(toolsDir, { withFileTypes: true });
const directories = entries
    .filter(entry => entry.isDirectory())
    .map(entry => entry.name)
    .filter(name => name !== 'base' && name !== 'utils'); // Exclude base/utils folders if they are not categories

// Sort alphabetically
directories.sort();

// Generate content
let content = `/**
 * MCP Unity Tools Index
 * Automatically generated by scripts/refresh-tools.js
 * 
 * To add a new category:
 * 1. Create a new directory under src/tools/
 * 2. Add an index.ts file in that directory
 * 3. Run 'npm run refresh-tools' (or node scripts/refresh-tools.js)
 */

// Base classes and utilities
export * from './base/BaseTool.js';
export * from './base/ToolRegistry.js';
export * from './base/ToolDecorators.js';

// Tool categories (alphabetically ordered)
`;

directories.forEach(dir => {
    // Check if index.ts exists in the directory
    if (fs.existsSync(path.join(toolsDir, dir, 'index.ts'))) {
        content += `export * from './${dir}/index.js';\n`;
    } else {
        console.warn(`⚠️  Warning: Directory '${dir}' exists but has no index.ts. Skipping.`);
    }
});

// Write file
fs.writeFileSync(indexFile, content);

console.log(`✅ Generated ${indexFile}`);
console.log(`   Included ${directories.length} categories.`);
